### ISSUE TITLE
router: support using `http.MethodGet`, `http.MethodPost` to replace "GET,POST" in `f.Routes`

### ISSUE THREAD

**Issue by unknwon** [flamego/flamego#113]
### Component

Core framework

### Middleware

n/a

### Is your feature request related to a problem? Please describe

To register a route for multiple HTTP methods, one would use follows:

```go
f.Routes("/", "GET,POST", ...)
```

However, the use of `"GET,POST"` looks very non-elegant, and one always needs to type in full characters without editor's auto-completion (because this is literal string).

### Describe the solution you'd like

The `net/http` package provides constants for each HTTP method, e.g. `http.MethodGet`, we should be able to do things more elegant like:

```go
f.Routes("/", http.MethodGet, http.MethodPost, <my handlers>)
```

Because these constants are strings after all, the router should be able to distinguished them from handlers, and magically do the trick for users.

### Describe alternatives you've considered

n/a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by byene0923** [comment]
I feel it's hard to do like
`f.Routes("/", http.MethodGet, http.MethodPost, <my handlers>)` 
because the second and third parameters are actual parameter and go can't support this
one way is change
`Routes(routePath, methods string, handlers ...Handler) *Route`
to
`Routes(routePath,  ...interface{}) *Route` and use reflect to check. i think it's non-elegant too.
or change it to arrays?

**Comment by unknwon** [comment]
I haven't thought well yet, maybe we are too constrained trying to solve the problem using a single method call.

Just thinking out loud, the following could probably work:

```go
f.Route("/").Methods(http.MethodGet, http.MethodPost).Handlers()
```

**Comment by unknwon** [comment]
Filed a new issue specifically addressing the problem of type-safe: https://github.com/flamego/flamego/issues/131
