### ISSUE TITLE
cors: doesn't check the port of URL while parsing `Access-Control-Allow-Origin`

### ISSUE THREAD

**Issue by m1dsummer** [flamego/flamego#116]
### Component

Middleware

### Middleware

https://github.com/flamego/cors

### Version

1.0.0

### Describe the bug

The cors middleware use `URL.Hostname()` to get hostname and then compare it with configured value of `AllowDomain`。

However, the result of `URL.Hostname()`  doesn't contain the `port` information.

According to [MDN Same OriginPolicy](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy), port(if specified)  is also a part of SOP.

```go
URL.Parse("http://example.com:8080").Hostname() // example.com, not example.com:8080
```

When `AllowDomain` is configured with a port(such as `example.com:8080`) and `Access-Control-Allow-Orogin` keeps the same as `AllowDomain`. The CORS check will always fail.

![image](https://user-images.githubusercontent.com/72367456/161915159-8a56989b-2b13-46e9-a0c0-4368af8b360a.png)

### To reproduce

First I create a simple flamego server and it runs at `http://0.0.0.0:2830`
```go
f := flamego.Classic()
	CORS := cors.CORS(cors.Options{
		Scheme:      "http",
		Methods:     []string{"GET", "POST", "OPTIONS"},
		AllowDomain: []string{"127.0.0.1:60012"},
	})
	f.Get("/", CORS, func(c flamego.Context) string {
		return "ok"
	})
	f.Run()
```

then I create a webpage and serve it at `http://127.0.0.1:60012/index.html`
```html
<body>
    <script>
        fetch("http://127.0.0.1:2830/")
    </script>
</body>
```

This is the request header copied from devtools:
```text
GET / HTTP/1.1
Host: 127.0.0.1:2830
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:99.0) Gecko/20100101 Firefox/99.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: http://127.0.0.1:60012/
Origin: http://127.0.0.1:60012
DNT: 1
Connection: keep-alive
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
Pragma: no-cache
Cache-Control: no-cache
```

The response from flamego is:
```text
HTTP/1.1 400 Bad Request
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Wed, 06 Apr 2022 07:23:36 GMT
Content-Length: 59

CORS request from prohibited domain http://127.0.0.1:60012
```

### Expected behavior

The backend should return `ok` with response code 200

### Additional context

source code: [cors middleware#line 99](https://github.com/flamego/cors/blob/b0fd74490ba8934b97f20bda17e83d2395b5d232/cors.go#L99)

Suggestion: use `URL.Hostname()+":"+URL.Port()` to get host while checking `Access-Control-Allow-Orogin` 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by unknwon** [comment]
Thanks for a high-quality bug report!

Please feel free to send a PR to fix this issue.
