### ISSUE TITLE
Returning a byte slice with an error outputs an empty HTTP body

### ISSUE THREAD

**Issue by asdine** [flamego/flamego#117]
### Component

Core framework

### Middleware

n/a

### Version

v1.1.0

### Describe the bug

I'm not sure if this is supported but when I'm using a handler that returns `([]byte, error)`, the response is empty.
It works when I only return `[]byte` though.

### To reproduce

```go
package main

import (
	"github.com/flamego/flamego"
)

func main() {
	f := flamego.Classic()

	f.Get("/", func() ([]byte, error) {
		return []byte(`{"hello": "world"}`), nil
	})

	f.Run()
}
```

### Expected behavior

See the output in the browser

### Additional context

Here are the relevant logs, we can see that the handler actually returns 0 bytes.

```
[Flamego] 2022-04-08 15:23:03: Started GET / for 100.100.100.100
[Flamego] 2022-04-08 15:23:03: Completed GET / 0  in 100.3µs
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by unknwon** [comment]
It [was not supported](https://github.com/flamego/flamego/blob/39a8db81540c6fc28099bc158336267f154439d6/return_handler.go#L34-L37) but I just added in https://github.com/flamego/flamego/pull/118!

**Comment by unknwon** [comment]
You can upgrade to https://github.com/flamego/flamego/releases/tag/v1.2.0 to use it 🎉

**Comment by unknwon** [comment]
Docs is also updated: https://flamego.dev/core-concepts.html#return-body-with-potential-error

**Comment by asdine** [comment]
Perfect timing! Thanks!
