### ISSUE TITLE
does flamego need to limit of uniqueness of injector.Map and injector.MapTo ?

### ISSUE THREAD

**Issue by byene0923** [flamego/flamego#122]
### Component

Core framework

### Middleware

https://github.com/flamego/

### Is your feature request related to a problem? Please describe

```
type User struct {
    Name string
}
Flame.Map(User{Name: "A"})
Flame.Map(User{Name: "B"})
```
user don't know which is used

### Describe the solution you'd like

```
func (inj *injector) Map(values ...interface{}) TypeMapper {
	for _, val := range values {
		if _, ok := inj.values[reflect.TypeOf(val)]; ok {
			panic(fmt.Sprintf("unable to map duplicate value: %v", reflect.TypeOf(val)))
		}
		inj.values[reflect.TypeOf(val)] = reflect.ValueOf(val)
	}
	return inj
}
```
same as MapTo

### Describe alternatives you've considered

support  multiple instances in long term?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by unknwon** [comment]
Thanks for the feedback!

However, being able to overwrite existing value in the injector is a _designated feature_: https://flamego.dev/custom-services.html#overriding-services
