### ISSUE TITLE
validator: make examples to work with i18n

### ISSUE THREAD

**Issue by unknwon** [flamego/flamego#128]
### Component

Middleware

### Middleware

https://github.com/flamego/validator

### Is your feature request related to a problem? Please describe

The validator module should be able to work with github.com/go-i18n/i18n and github.com/flamego/i18n, we need to make some example or make code changes to make that happen.

### Describe the solution you'd like

n/a

### Describe alternatives you've considered

n/a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by unknwon** [comment]
@wuyunhua1987 Example is now in the docs: https://flamego.dev/middleware/binding.html#localize-validation-errors

**Comment by wuyunhua1987** [comment]
thank you very much, good job!!!
