### ISSUE TITLE
router: add support for `HeadersRegexp`

### ISSUE THREAD

**Issue by diluga** [flamego/flamego#132]
### Component

Core framework

### Middleware

n/a

### Is your feature request related to a problem? Please describe

hi,
it that any plan to support router with HeadersRegexp?
i want to write S3 web service (looks like minio) with flamego ,but it miss HeadersRegexp func to filter request with header.

https://github.com/minio/minio/blob/master/cmd/api-router.go#L242

```go
// HeadersRegexp accepts a sequence of key/value pairs, where the value has regex
// support. For example:
//
//     r := mux.NewRouter()
//     r.HeadersRegexp("Content-Type", "application/(text|json)",
//               "X-Requested-With", "XMLHttpRequest")
//
// The above route will only match if both the request header matches both regular expressions.
// If the value is an empty string, it will match any value if the key is set.
// Use the start and end of string anchors (^ and $) to match an exact value.
```

### Describe the solution you'd like

https://github.com/gorilla/mux/blob/d07530f46e1eec4e40346e24af34dcc6750ad39f/route.go#L255

### Describe alternatives you've considered

https://github.com/minio/minio/blob/master/cmd/api-router.go#L242

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by unknwon** [comment]
TIL `HeadersRegexp`, thanks for the feedback!

**Comment by unknwon** [comment]
Before docs are up, please refer to https://github.com/flamego/flamego/blob/92b5d1471931f6a34af3cd361c5e867e0d3e745b/router.go#L142-L155 how to use it.
