### ISSUE TITLE
Bump go version to 1.19

### ISSUE THREAD

**Issue by pawelbeza** [flamego/flamego#148]
### Component

Core framework

### Middleware

https://github.com/flamego/

### Is your feature request related to a problem? Please describe

Current implementation of flamego doesn't support go 1.19

vendor/github.com/flamego/flamego/internal/route/parser.go:15:10: cannot use generic type participle.Parser[G any] without instantiation
vendor/github.com/flamego/flamego/internal/route/parser.go:65:33: implicit function instantiation requires go1.18 or later (-lang was set to go1.16; check go.mod)
vendor/github.com/flamego/flamego/internal/route/parser.go:65:33: cannot infer G (/Users/pbeza/Documents/go-nerve/vendor/github.com/alecthomas/participle/v2/parser.go:65:12)

### Describe the solution you'd like

bump go version to 1.19 or/and resolve issues above

### Describe alternatives you've considered

-

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by unknwon** [comment]
Thanks for the feedback!

You can now use go get github.com/flamego/flamego@v1.7.0 to use a version that is compatible with Go >= 1.18.
