### ISSUE TITLE
Encountered a GOB error when using Session and CSRF at the same time

### ISSUE THREAD

**Issue by asjdf** [flamego/flamego#152]
### Component

Middleware

### Middleware

https://github.com/flamego/session

### Version

1.2.1

### Describe the bug

在使用redis存储session时遇到问题 `gob: type not registered for interface: time.Time` 

### To reproduce

配置 session 使用 Redis 作为存储。
然后后部加上csrf。
可在flamego/session/redis/redis.go:68 下断点复现。
![image](https://user-images.githubusercontent.com/22193008/203052536-5f19cd36-d027-4b81-a8e6-a3366d0603ae.png)

### Expected behavior

正常应该无报错

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by asjdf** [comment]
看起来使用 memery 存储 session 是因为并没有转换的部分

**Comment by asjdf** [comment]
想解决这个问题似乎需要在 session/type.go 中使用 gob 进行 encode/decode 之前 执行gob.Register(time.Time{})，或对 csrf 包动刀

**Comment by unknwon** [comment]
Thanks for the report!

This problem should have been fixed in the v1.1.1 version of the CSRF package:

```
go get github.com/flamego/csrf@v1.1.1
```
