### ISSUE TITLE
binding: support YAML format

### ISSUE THREAD

**Issue by unknwon** [flamego/flamego#72]
### Component

Middleware

### Middleware

https://github.com/flamego/binding

### Is your feature request related to a problem? Please describe

YAML is a popular data exchange format besides JSON and XML.

### Describe the solution you'd like

Building on top of `gopkg.in/yaml.v2` similar to what have been implemented in https://github.com/go-macaron/binding/pull/40.

### Describe alternatives you've considered

Live with it.

### Additional context

Feel free to ask more details or clarifying questions!

If you would like to contribute on the implementation, please:

1. Comment on the issue for taking the responsibility so everyone knows.
1. Acknowledge that the expected timeline is one week.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Germiniku** [comment]
I write this issue and submit pr  link: https://github.com/flamego/binding/pull/16
