### ISSUE TITLE
session: support auto-create table for PostgreSQL and MySQL

### ISSUE THREAD

**Issue by unknwon** [flamego/flamego#81]
### Component

Middleware

### Middleware

https://github.com/flamego/session

### Is your feature request related to a problem? Please describe

The session middleware require manual creation of the table for PostgreSQL and MySQL backend.

### Describe the solution you'd like

Add an option to the [`postgres.Config`](https://github.com/flamego/session/blob/22e773287cf151692d5d848e31e994a75edc9d6c/postgres/postgres.go#L112) and [`mysql.Config`](https://github.com/flamego/session/blob/22e773287cf151692d5d848e31e994a75edc9d6c/mysql/mysql.go#L128) like the following (field name need to be discussed):

```go
type Config struct{
	// ...
	InitTable bool
}
```

Which automatically creates the table when not exists.

The SQL to create the table can be [derived from the tests](https://github.com/flamego/session/blob/22e773287cf151692d5d848e31e994a75edc9d6c/postgres/postgres_test.go#L70-L73).

### Describe alternatives you've considered

Live with it.

### Additional context

Feel free to ask more details or clarifying questions!

If you would like to contribute on the implementation, please:

1. Comment on the issue for taking the responsibility so everyone knows.
1. Acknowledge that the expected timeline is one week.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by noneback** [comment]
I have no experience about web framwork, but I'm interested in this project. Can pick it up? I will try my best in my spare time.

**Comment by unknwon** [comment]
@noneback of course you can!

FYI This particular task isn’t strictly related to any web technology, it is more of general Go and database.

**Comment by noneback** [comment]
I have finished it recently. Hope you can review it at your convenience.
https://github.com/flamego/session/pull/22
