### ISSUE TITLE
cache: support auto-create table for PostgreSQL and MySQL

### ISSUE THREAD

**Issue by unknwon** [flamego/flamego#82]
### Component

Middleware

### Middleware

https://github.com/flamego/cache

### Is your feature request related to a problem? Please describe

The cache middleware require manual creation of the table for PostgreSQL and MySQL backend.

### Describe the solution you'd like

Add an option to the [`postgres.Config`](https://github.com/flamego/cache/blob/76ab4d40e5864da59f0db93e470b334cf0fa7c4e/postgres/postgres.go#L113) and [`mysql.Config`](https://github.com/flamego/cache/blob/76ab4d40e5864da59f0db93e470b334cf0fa7c4e/mysql/mysql.go#L122) like the following (field name need to be discussed):

```go
type Config struct{
	// ...
	InitTable bool
}
```

Which automatically creates the table when not exists.

Notes:
- The SQL to create the table can be [derived from the tests](https://github.com/flamego/cache/blob/76ab4d40e5864da59f0db93e470b334cf0fa7c4e/postgres/postgres_test.go#L71-L74).
- The implementation would be very similar to https://github.com/flamego/session/pull/22.

### Describe alternatives you've considered

Live with it.

### Additional context

Feel free to ask more details or clarifying questions!

If you would like to contribute on the implementation, please:

1. Comment on the issue for taking the responsibility so everyone knows.
1. Acknowledge that the expected timeline is one week.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by unknwon** [comment]
@NoneBack Do you wanna give this issue a try? The implementation would be very similar to your PR https://github.com/flamego/session/pull/22.

**Comment by noneback** [comment]
Sure. I will try in my spare time.
